//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.sponsors = new HashSet<sponsor>();
            this.users = new HashSet<user>();
        }
    
        public long addressID { get; set; }
        public string line1 { get; set; }
        public string line2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
    
        public virtual ICollection<sponsor> sponsors { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
