//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrator
    {
        public int administratorsID { get; set; }
        public int priviledgesID { get; set; }
        public long membershipID { get; set; }
    
        public virtual membership membership { get; set; }
        public virtual priviledge priviledge { get; set; }
    }
}
