//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class authorizationsubmitted
    {
        public int authorizationSubmittedID { get; set; }
        public long minorID { get; set; }
        public string documentFile { get; set; }
        public string documentName { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
    
        public virtual minor minor { get; set; }
    }
}
