//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class committeeinterface
    {
        public int committeID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string affiliation { get; set; }
        public string description { get; set; }
    }
}
