//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class companionminor
    {
        public int companionminorID { get; set; }
        public Nullable<long> minorID { get; set; }
        public Nullable<long> companionID { get; set; }
    
        public virtual companion companion { get; set; }
        public virtual minor minor { get; set; }
    }
}
