//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class complementarykey
    {
        public long complementarykeyID { get; set; }
        public long sponsorID { get; set; }
        public string isUsed { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> deleitionDate { get; set; }
    
        public virtual paymentcomplementary paymentcomplementary { get; set; }
        public virtual sponsor sponsor { get; set; }
    }
}
