//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class companion
    {
        public companion()
        {
            this.companionminors = new HashSet<companionminor>();
        }
    
        public long companionID { get; set; }
        public Nullable<long> userID { get; set; }
        public string companionKey { get; set; }
    
        public virtual ICollection<companionminor> companionminors { get; set; }
        public virtual user user { get; set; }
    }
}
