//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluationsubmitted
    {
        public long evaluationsubmittedID { get; set; }
        public long evaluatiorSubmissionID { get; set; }
        public string evaluationFile { get; set; }
        public Nullable<int> score { get; set; }
        public string publicFeedback { get; set; }
        public string privateFeedback { get; set; }
    
        public virtual evaluatiorsubmission evaluatiorsubmission { get; set; }
    }
}
