//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluator
    {
        public evaluator()
        {
            this.evaluatiorsubmissions = new HashSet<evaluatiorsubmission>();
        }
    
        public long evaluatorsID { get; set; }
        public long userID { get; set; }
    
        public virtual ICollection<evaluatiorsubmission> evaluatiorsubmissions { get; set; }
        public virtual user user { get; set; }
    }
}
