//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class membershiptype
    {
        public membershiptype()
        {
            this.memberships = new HashSet<membership>();
        }
    
        public int membershipTypeID { get; set; }
        public string membershipTypeName { get; set; }
    
        public virtual ICollection<membership> memberships { get; set; }
    }
}
