//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership
    {
        public membership()
        {
            this.administrators = new HashSet<administrator>();
            this.users = new HashSet<user>();
        }
    
        public long membershipID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
        public Nullable<int> membershipTypeID { get; set; }
        public string emailConfirmation { get; set; }
    
        public virtual ICollection<administrator> administrators { get; set; }
        public virtual ICollection<user> users { get; set; }
        public virtual membershiptype membershiptype { get; set; }
    }
}
