//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class minor
    {
        public minor()
        {
            this.authorizationsubmitteds = new HashSet<authorizationsubmitted>();
            this.companionminors = new HashSet<companionminor>();
        }
    
        public long minorsID { get; set; }
        public long userID { get; set; }
        public string authorizationStatus { get; set; }
    
        public virtual ICollection<authorizationsubmitted> authorizationsubmitteds { get; set; }
        public virtual ICollection<companionminor> companionminors { get; set; }
        public virtual user user { get; set; }
    }
}
