//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class panel
    {
        public long panelsID { get; set; }
        public long submissionID { get; set; }
        public string panelistNames { get; set; }
        public string plan { get; set; }
        public string guideQuestion { get; set; }
        public string formatDescription { get; set; }
        public string necessaryEquipment { get; set; }
    
        public virtual submission submission { get; set; }
    }
}
