//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentbill
    {
        public long paymentBillID { get; set; }
        public long paymentID { get; set; }
        public string transactionid { get; set; }
        public int AmountPaid { get; set; }
        public string methodOfPayment { get; set; }
        public string creditCardNumber { get; set; }
    
        public virtual payment payment { get; set; }
    }
}
