//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentcomplementary
    {
        public long paymentcomplementaryID { get; set; }
        public long paymentID { get; set; }
        public long complementaryKeyID { get; set; }
    
        public virtual complementarykey complementarykey { get; set; }
        public virtual payment payment { get; set; }
    }
}
