//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public payment()
        {
            this.paymentcomplementaries = new HashSet<paymentcomplementary>();
            this.paymentbills = new HashSet<paymentbill>();
            this.registrations = new HashSet<registration>();
            this.sponsors = new HashSet<sponsor>();
        }
    
        public long paymentID { get; set; }
        public int paymentTypeID { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> deletionDate { get; set; }
    
        public virtual ICollection<paymentcomplementary> paymentcomplementaries { get; set; }
        public virtual ICollection<paymentbill> paymentbills { get; set; }
        public virtual ICollection<registration> registrations { get; set; }
        public virtual ICollection<sponsor> sponsors { get; set; }
        public virtual paymenttype paymenttype { get; set; }
    }
}
