//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class sponsortype
    {
        public sponsortype()
        {
            this.sponsors = new HashSet<sponsor>();
        }
    
        public int sponsortypeID { get; set; }
        public string name { get; set; }
        public string amount { get; set; }
        public string benefit1 { get; set; }
        public string benefit2 { get; set; }
        public string benefit3 { get; set; }
        public string benefit4 { get; set; }
        public string benefit5 { get; set; }
        public string sponsortypecol { get; set; }
    
        public virtual ICollection<sponsor> sponsors { get; set; }
    }
}
