//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class submission
    {
        public submission()
        {
            this.documentssubmitteds = new HashSet<documentssubmitted>();
            this.evaluatiorsubmissions = new HashSet<evaluatiorsubmission>();
            this.panels = new HashSet<panel>();
            this.templatesubmissions = new HashSet<templatesubmission>();
            this.workshops = new HashSet<workshop>();
        }
    
        public long submissionID { get; set; }
        public long userID { get; set; }
        public int topicID { get; set; }
        public int submissionTypeID { get; set; }
        public string hasApplied { get; set; }
        public string title { get; set; }
        public string status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> deleitionDate { get; set; }
    
        public virtual ICollection<documentssubmitted> documentssubmitteds { get; set; }
        public virtual ICollection<evaluatiorsubmission> evaluatiorsubmissions { get; set; }
        public virtual ICollection<panel> panels { get; set; }
        public virtual ICollection<templatesubmission> templatesubmissions { get; set; }
        public virtual submissiontype submissiontype { get; set; }
        public virtual ICollection<workshop> workshops { get; set; }
        public virtual topiccategory topiccategory { get; set; }
    }
}
