//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class topiccategory
    {
        public topiccategory()
        {
            this.submissions = new HashSet<submission>();
        }
    
        public int topiccategoryID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<submission> submissions { get; set; }
    }
}
