//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertype
    {
        public usertype()
        {
            this.users = new HashSet<user>();
        }
    
        public int userTypeID { get; set; }
        public string userTypeName { get; set; }
        public string description { get; set; }
        public Nullable<int> registrationCost { get; set; }
        public Nullable<int> registrationLateFee { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
