//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.companions = new HashSet<companion>();
            this.evaluators = new HashSet<evaluator>();
            this.minors = new HashSet<minor>();
            this.registrations = new HashSet<registration>();
        }
    
        public long userID { get; set; }
        public long membershipID { get; set; }
        public Nullable<long> addressID { get; set; }
        public int userTypeID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string affiliationName { get; set; }
        public string phone { get; set; }
        public string userFax { get; set; }
        public string registrationStatus { get; set; }
        public string hasApplied { get; set; }
        public string acceptanceStatus { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<companion> companions { get; set; }
        public virtual ICollection<evaluator> evaluators { get; set; }
        public virtual membership membership { get; set; }
        public virtual ICollection<minor> minors { get; set; }
        public virtual ICollection<registration> registrations { get; set; }
        public virtual usertype usertype { get; set; }
    }
}
