//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NancyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class workshop
    {
        public int workshopID { get; set; }
        public long submissionID { get; set; }
        public string duration { get; set; }
        public string delivery { get; set; }
        public string plan { get; set; }
        public string necessary_equipment { get; set; }
    
        public virtual submission submission { get; set; }
    }
}
